name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}